//! Const-generated byte/state transition table for the VT parser.
//!
//! The generation order follows Ghostty's parse_table.zig and the vt100.net
//! DEC ANSI parser table. Duplicate cells fail const evaluation, except for
//! OSC C1/UTF-8 data bytes where Ghostty intentionally uses last-write-wins.

use super::{state_from_index, State, TransitionAction, STATE_COUNT};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Transition {
    pub state: State,
    pub action: TransitionAction,
}

pub const TABLE: [[Transition; STATE_COUNT]; 256] = generate_table();

const fn generate_table() -> [[Transition; STATE_COUNT]; 256] {
    let mut table = [[None; STATE_COUNT]; 256];

    let mut state_index = 0;
    while state_index < STATE_COUNT {
        let source = state_from_index(state_index);
        single(
            &mut table,
            0x18,
            source,
            State::Ground,
            TransitionAction::Execute,
        );
        single(
            &mut table,
            0x1A,
            source,
            State::Ground,
            TransitionAction::Execute,
        );
        range(
            &mut table,
            0x80,
            0x8F,
            source,
            State::Ground,
            TransitionAction::Execute,
        );
        range(
            &mut table,
            0x91,
            0x97,
            source,
            State::Ground,
            TransitionAction::Execute,
        );
        single(
            &mut table,
            0x99,
            source,
            State::Ground,
            TransitionAction::Execute,
        );
        single(
            &mut table,
            0x9A,
            source,
            State::Ground,
            TransitionAction::Execute,
        );
        single(
            &mut table,
            0x9C,
            source,
            State::Ground,
            TransitionAction::None,
        );
        single(
            &mut table,
            0x1B,
            source,
            State::Escape,
            TransitionAction::None,
        );
        single(
            &mut table,
            0x98,
            source,
            State::SosPmApcString,
            TransitionAction::None,
        );
        single(
            &mut table,
            0x9E,
            source,
            State::SosPmApcString,
            TransitionAction::None,
        );
        single(
            &mut table,
            0x9F,
            source,
            State::SosPmApcString,
            TransitionAction::None,
        );
        single(
            &mut table,
            0x9B,
            source,
            State::CsiEntry,
            TransitionAction::None,
        );
        single(
            &mut table,
            0x90,
            source,
            State::DcsEntry,
            TransitionAction::None,
        );
        single(
            &mut table,
            0x9D,
            source,
            State::OscString,
            TransitionAction::None,
        );
        state_index += 1;
    }

    range(
        &mut table,
        0x00,
        0x17,
        State::Ground,
        State::Ground,
        TransitionAction::Execute,
    );
    single(
        &mut table,
        0x19,
        State::Ground,
        State::Ground,
        TransitionAction::Execute,
    );
    range(
        &mut table,
        0x1C,
        0x1F,
        State::Ground,
        State::Ground,
        TransitionAction::Execute,
    );
    range(
        &mut table,
        0x20,
        0x7F,
        State::Ground,
        State::Ground,
        TransitionAction::Print,
    );

    let source = State::EscapeIntermediate;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Execute,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Execute);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Execute,
    );
    range(
        &mut table,
        0x20,
        0x2F,
        source,
        source,
        TransitionAction::Collect,
    );
    single(&mut table, 0x7F, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x30,
        0x7E,
        source,
        State::Ground,
        TransitionAction::EscDispatch,
    );

    let source = State::SosPmApcString;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::ApcPut,
    );
    single(&mut table, 0x19, source, source, TransitionAction::ApcPut);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::ApcPut,
    );
    range(
        &mut table,
        0x20,
        0x7F,
        source,
        source,
        TransitionAction::ApcPut,
    );

    let source = State::Escape;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Execute,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Execute);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Execute,
    );
    single(&mut table, 0x7F, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x30,
        0x4F,
        source,
        State::Ground,
        TransitionAction::EscDispatch,
    );
    range(
        &mut table,
        0x51,
        0x57,
        source,
        State::Ground,
        TransitionAction::EscDispatch,
    );
    single(
        &mut table,
        0x59,
        source,
        State::Ground,
        TransitionAction::EscDispatch,
    );
    single(
        &mut table,
        0x5A,
        source,
        State::Ground,
        TransitionAction::EscDispatch,
    );
    single(
        &mut table,
        0x5C,
        source,
        State::Ground,
        TransitionAction::EscDispatch,
    );
    range(
        &mut table,
        0x60,
        0x7E,
        source,
        State::Ground,
        TransitionAction::EscDispatch,
    );
    range(
        &mut table,
        0x20,
        0x2F,
        source,
        State::EscapeIntermediate,
        TransitionAction::Collect,
    );
    single(
        &mut table,
        0x58,
        source,
        State::SosPmApcString,
        TransitionAction::None,
    );
    single(
        &mut table,
        0x5E,
        source,
        State::SosPmApcString,
        TransitionAction::None,
    );
    single(
        &mut table,
        0x5F,
        source,
        State::SosPmApcString,
        TransitionAction::None,
    );
    single(
        &mut table,
        0x50,
        source,
        State::DcsEntry,
        TransitionAction::None,
    );
    single(
        &mut table,
        0x5B,
        source,
        State::CsiEntry,
        TransitionAction::None,
    );
    single(
        &mut table,
        0x5D,
        source,
        State::OscString,
        TransitionAction::None,
    );

    let source = State::DcsEntry;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Ignore,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Ignore,
    );
    single(&mut table, 0x7F, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x20,
        0x2F,
        source,
        State::DcsIntermediate,
        TransitionAction::Collect,
    );
    single(
        &mut table,
        0x3A,
        source,
        State::DcsIgnore,
        TransitionAction::None,
    );
    range(
        &mut table,
        0x30,
        0x39,
        source,
        State::DcsParam,
        TransitionAction::Param,
    );
    single(
        &mut table,
        0x3B,
        source,
        State::DcsParam,
        TransitionAction::Param,
    );
    range(
        &mut table,
        0x3C,
        0x3F,
        source,
        State::DcsParam,
        TransitionAction::Collect,
    );
    range(
        &mut table,
        0x40,
        0x7E,
        source,
        State::DcsPassthrough,
        TransitionAction::None,
    );

    let source = State::DcsIntermediate;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Ignore,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Ignore,
    );
    range(
        &mut table,
        0x20,
        0x2F,
        source,
        source,
        TransitionAction::Collect,
    );
    single(&mut table, 0x7F, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x30,
        0x3F,
        source,
        State::DcsIgnore,
        TransitionAction::None,
    );
    range(
        &mut table,
        0x40,
        0x7E,
        source,
        State::DcsPassthrough,
        TransitionAction::None,
    );

    let source = State::DcsIgnore;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Ignore,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Ignore,
    );

    let source = State::DcsParam;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Ignore,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Ignore,
    );
    range(
        &mut table,
        0x30,
        0x39,
        source,
        source,
        TransitionAction::Param,
    );
    single(&mut table, 0x3B, source, source, TransitionAction::Param);
    single(&mut table, 0x7F, source, source, TransitionAction::Ignore);
    single(
        &mut table,
        0x3A,
        source,
        State::DcsIgnore,
        TransitionAction::None,
    );
    range(
        &mut table,
        0x3C,
        0x3F,
        source,
        State::DcsIgnore,
        TransitionAction::None,
    );
    range(
        &mut table,
        0x20,
        0x2F,
        source,
        State::DcsIntermediate,
        TransitionAction::Collect,
    );
    range(
        &mut table,
        0x40,
        0x7E,
        source,
        State::DcsPassthrough,
        TransitionAction::None,
    );

    let source = State::DcsPassthrough;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Put,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Put);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Put,
    );
    range(
        &mut table,
        0x20,
        0x7E,
        source,
        source,
        TransitionAction::Put,
    );
    single(&mut table, 0x7F, source, source, TransitionAction::Ignore);

    let source = State::CsiParam;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Execute,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Execute);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Execute,
    );
    range(
        &mut table,
        0x30,
        0x39,
        source,
        source,
        TransitionAction::Param,
    );
    // Ghostty accepts ':' in CSI params for colon-form SGR color sequences.
    single(&mut table, 0x3A, source, source, TransitionAction::Param);
    single(&mut table, 0x3B, source, source, TransitionAction::Param);
    single(&mut table, 0x7F, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x40,
        0x7E,
        source,
        State::Ground,
        TransitionAction::CsiDispatch,
    );
    range(
        &mut table,
        0x3C,
        0x3F,
        source,
        State::CsiIgnore,
        TransitionAction::None,
    );
    range(
        &mut table,
        0x20,
        0x2F,
        source,
        State::CsiIntermediate,
        TransitionAction::Collect,
    );

    let source = State::CsiIgnore;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Execute,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Execute);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Execute,
    );
    range(
        &mut table,
        0x20,
        0x3F,
        source,
        source,
        TransitionAction::Ignore,
    );
    single(&mut table, 0x7F, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x40,
        0x7E,
        source,
        State::Ground,
        TransitionAction::None,
    );

    let source = State::CsiIntermediate;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Execute,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Execute);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Execute,
    );
    range(
        &mut table,
        0x20,
        0x2F,
        source,
        source,
        TransitionAction::Collect,
    );
    single(&mut table, 0x7F, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x40,
        0x7E,
        source,
        State::Ground,
        TransitionAction::CsiDispatch,
    );
    range(
        &mut table,
        0x30,
        0x3F,
        source,
        State::CsiIgnore,
        TransitionAction::None,
    );

    let source = State::CsiEntry;
    range(
        &mut table,
        0x00,
        0x17,
        source,
        source,
        TransitionAction::Execute,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Execute);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Execute,
    );
    single(&mut table, 0x7F, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x40,
        0x7E,
        source,
        State::Ground,
        TransitionAction::CsiDispatch,
    );
    single(
        &mut table,
        0x3A,
        source,
        State::CsiIgnore,
        TransitionAction::None,
    );
    range(
        &mut table,
        0x20,
        0x2F,
        source,
        State::CsiIntermediate,
        TransitionAction::Collect,
    );
    range(
        &mut table,
        0x30,
        0x39,
        source,
        State::CsiParam,
        TransitionAction::Param,
    );
    single(
        &mut table,
        0x3B,
        source,
        State::CsiParam,
        TransitionAction::Param,
    );
    range(
        &mut table,
        0x3C,
        0x3F,
        source,
        State::CsiParam,
        TransitionAction::Collect,
    );

    let source = State::OscString;
    range(
        &mut table,
        0x00,
        0x06,
        source,
        source,
        TransitionAction::Ignore,
    );
    range(
        &mut table,
        0x08,
        0x17,
        source,
        source,
        TransitionAction::Ignore,
    );
    single(&mut table, 0x19, source, source, TransitionAction::Ignore);
    range(
        &mut table,
        0x1C,
        0x1F,
        source,
        source,
        TransitionAction::Ignore,
    );
    range(
        &mut table,
        0x20,
        0x7F,
        source,
        source,
        TransitionAction::OscPut,
    );
    // OSC strings carry UTF-8/C1 bytes as data. This intentionally overwrites
    // the "anywhere" transitions for 0x80..0x9F, including 0x9C ST.
    overwrite_range(
        &mut table,
        0x80,
        0xFF,
        source,
        source,
        TransitionAction::OscPut,
    );
    // XTerm accepts BEL or ST for terminating OSC sequences.
    single(
        &mut table,
        0x07,
        source,
        State::Ground,
        TransitionAction::None,
    );

    let mut final_table = [[Transition {
        state: State::Ground,
        action: TransitionAction::None,
    }; STATE_COUNT]; 256];
    let mut byte = 0usize;
    while byte < 256 {
        let mut column = 0usize;
        while column < STATE_COUNT {
            final_table[byte][column] = match table[byte][column] {
                Some(transition) => transition,
                None => Transition {
                    state: state_from_index(column),
                    action: TransitionAction::None,
                },
            };
            column += 1;
        }
        byte += 1;
    }
    final_table
}

const fn single(
    table: &mut [[Option<Transition>; STATE_COUNT]; 256],
    byte: u8,
    source: State,
    target: State,
    action: TransitionAction,
) {
    let cell = &mut table[byte as usize][source as usize];
    if cell.is_some() {
        panic!("duplicate transition");
    }
    *cell = Some(Transition {
        state: target,
        action,
    });
}

const fn range(
    table: &mut [[Option<Transition>; STATE_COUNT]; 256],
    from: u8,
    to: u8,
    source: State,
    target: State,
    action: TransitionAction,
) {
    let mut byte = from;
    loop {
        single(table, byte, source, target, action);
        if byte == to {
            break;
        }
        byte += 1;
    }
}

const fn overwrite_range(
    table: &mut [[Option<Transition>; STATE_COUNT]; 256],
    from: u8,
    to: u8,
    source: State,
    target: State,
    action: TransitionAction,
) {
    let mut byte = from;
    loop {
        table[byte as usize][source as usize] = Some(Transition {
            state: target,
            action,
        });
        if byte == to {
            break;
        }
        byte += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::{Transition, TABLE};
    use crate::parser::{State, TransitionAction};

    #[test]
    fn table_routes_esc_from_ground_to_escape() {
        assert_eq!(
            TABLE[0x1B][State::Ground as usize],
            Transition {
                state: State::Escape,
                action: TransitionAction::None,
            }
        );
    }

    #[test]
    fn table_prints_ascii_in_ground() {
        assert_eq!(
            TABLE[b'a' as usize][State::Ground as usize],
            Transition {
                state: State::Ground,
                action: TransitionAction::Print,
            }
        );
    }

    #[test]
    fn table_routes_colon_to_param_inside_csi_param() {
        assert_eq!(
            TABLE[0x3A][State::CsiParam as usize],
            Transition {
                state: State::CsiParam,
                action: TransitionAction::Param,
            }
        );
    }

    #[test]
    fn table_bel_terminates_osc() {
        assert_eq!(
            TABLE[0x07][State::OscString as usize],
            Transition {
                state: State::Ground,
                action: TransitionAction::None,
            }
        );
    }

    #[test]
    fn table_st_terminates_dcs_passthrough() {
        assert_eq!(
            TABLE[0x9C][State::DcsPassthrough as usize],
            Transition {
                state: State::Ground,
                action: TransitionAction::None,
            }
        );
    }

    #[test]
    fn table_treats_st_as_data_inside_osc() {
        assert_eq!(
            TABLE[0x9C][State::OscString as usize],
            Transition {
                state: State::OscString,
                action: TransitionAction::OscPut,
            }
        );
    }
}
