//! Keyboard event types used by terminal input encoders.

use super::key_mods::Mods;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Action {
    Release,
    #[default]
    Press,
    Repeat,
}

#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum Key {
    #[default]
    Unidentified,
    Backquote,
    Backslash,
    BracketLeft,
    BracketRight,
    Comma,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Equal,
    IntlBackslash,
    IntlRo,
    IntlYen,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,
    AltLeft,
    AltRight,
    Backspace,
    CapsLock,
    ContextMenu,
    ControlLeft,
    ControlRight,
    Enter,
    MetaLeft,
    MetaRight,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    Convert,
    KanaMode,
    NonConvert,
    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadSubtract,
    NumpadSeparator,
    NumpadUp,
    NumpadDown,
    NumpadRight,
    NumpadLeft,
    NumpadBegin,
    NumpadHome,
    NumpadEnd,
    NumpadInsert,
    NumpadDelete,
    NumpadPageUp,
    NumpadPageDown,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    Fn,
    FnLock,
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,
    Eject,
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,
    PrintScreen,
    ScrollLock,
    Pause,
    Copy,
    Cut,
    Paste,
}

impl Key {
    pub const fn codepoint(self) -> Option<u32> {
        match self {
            Self::KeyA => Some('a' as u32),
            Self::KeyB => Some('b' as u32),
            Self::KeyC => Some('c' as u32),
            Self::KeyD => Some('d' as u32),
            Self::KeyE => Some('e' as u32),
            Self::KeyF => Some('f' as u32),
            Self::KeyG => Some('g' as u32),
            Self::KeyH => Some('h' as u32),
            Self::KeyI => Some('i' as u32),
            Self::KeyJ => Some('j' as u32),
            Self::KeyK => Some('k' as u32),
            Self::KeyL => Some('l' as u32),
            Self::KeyM => Some('m' as u32),
            Self::KeyN => Some('n' as u32),
            Self::KeyO => Some('o' as u32),
            Self::KeyP => Some('p' as u32),
            Self::KeyQ => Some('q' as u32),
            Self::KeyR => Some('r' as u32),
            Self::KeyS => Some('s' as u32),
            Self::KeyT => Some('t' as u32),
            Self::KeyU => Some('u' as u32),
            Self::KeyV => Some('v' as u32),
            Self::KeyW => Some('w' as u32),
            Self::KeyX => Some('x' as u32),
            Self::KeyY => Some('y' as u32),
            Self::KeyZ => Some('z' as u32),
            Self::Digit0 | Self::Numpad0 => Some('0' as u32),
            Self::Digit1 | Self::Numpad1 => Some('1' as u32),
            Self::Digit2 | Self::Numpad2 => Some('2' as u32),
            Self::Digit3 | Self::Numpad3 => Some('3' as u32),
            Self::Digit4 | Self::Numpad4 => Some('4' as u32),
            Self::Digit5 | Self::Numpad5 => Some('5' as u32),
            Self::Digit6 | Self::Numpad6 => Some('6' as u32),
            Self::Digit7 | Self::Numpad7 => Some('7' as u32),
            Self::Digit8 | Self::Numpad8 => Some('8' as u32),
            Self::Digit9 | Self::Numpad9 => Some('9' as u32),
            Self::Semicolon => Some(';' as u32),
            Self::Space => Some(' ' as u32),
            Self::Quote => Some('\'' as u32),
            Self::Comma => Some(',' as u32),
            Self::Backquote => Some('`' as u32),
            Self::Period | Self::NumpadDecimal => Some('.' as u32),
            Self::Slash | Self::NumpadDivide => Some('/' as u32),
            Self::Minus | Self::NumpadSubtract => Some('-' as u32),
            Self::Equal | Self::NumpadEqual => Some('=' as u32),
            Self::BracketLeft => Some('[' as u32),
            Self::BracketRight => Some(']' as u32),
            Self::Backslash => Some('\\' as u32),
            Self::Tab => Some('\t' as u32),
            Self::NumpadMultiply => Some('*' as u32),
            Self::NumpadAdd => Some('+' as u32),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct KeyEvent<'a> {
    pub action: Action,
    pub key: Key,
    pub mods: Mods,
    pub consumed_mods: Mods,
    pub composing: bool,
    pub utf8: &'a [u8],
    pub unshifted_codepoint: u32,
}

impl<'a> Default for KeyEvent<'a> {
    fn default() -> Self {
        Self {
            action: Action::Press,
            key: Key::Unidentified,
            mods: Mods::none(),
            consumed_mods: Mods::none(),
            composing: false,
            utf8: b"",
            unshifted_codepoint: 0,
        }
    }
}

impl<'a> KeyEvent<'a> {
    pub fn effective_mods(self) -> Mods {
        if self.utf8.is_empty() {
            self.mods
        } else {
            self.mods.unset(self.consumed_mods)
        }
    }
}
